version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rssp
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    logging:
      driver: none
volumes:
  mysql-volume:
